#config_version=5
##! mode: base

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  s_adv_bounus_roll_over_active:
    bonus: 1
      
score_queue_player:
  score_10_points:
    score: 10
  score_50_points:
    score: 50
  s_right_inner_outline_active:
    score: 100 
  s_left_inner_outline_active:
    score: 100 
  s_left_center_drop_target_active:
    score: 1000
  s_left_out_top_drop_target_active:
    score: 1000 
  s_left_in_top_drop_target_active:
    score: 1000 
  s_right_in_top_drop_target_active:
    score: 1000 
  s_right_out_top_drop_target_active:
    score: 1000 
  score_spinner:
    score: 100 
  score_saucer:
    score: 5000 
  score_outlane:
    score: 5000 
  score_inlane:
    score: 5000 
  score_slingshot:
    score: 10 
  score_thumper:
    score: 1000
  score_advance_bonus:
    score: 1000

light_player:
  "{current_player.bonus%10>=1}":
    l_bonus_10000: on
  "{current_player.bonus%10>=2}":
    l_bonus_20000: on
  "{current_player.bonus%10>=3}":
    l_bonus_30000: on
  "{current_player.bonus%10>=4}":
    l_bonus_40000: on
  "{current_player.bonus%10>=5}":
    l_bonus_50000: on
  "{current_player.bonus%10>=6}":
    l_bonus_60000: on
  "{current_player.bonus%10>=7}":
    l_bonus_70000: on
  "{current_player.bonus%10>=8}":
    l_bonus_80000: on
  "{current_player.bonus%10>=9}":
    l_bonus_90000: on
  "{current_player.bonus>=10}":
    l_bonus_100000: on

  
  
