#config_version=5
##! mode: base

mode:
  start_events: ball_starting
  priority: 100
  
queue_relay_player:
  balldevice_bd_right_saucer_ball_eject_attempt:
    post: right_saucer_feature_started
    wait_for: right_saucer_feature_ended
  balldevice_bd_top_saucer_ball_eject_attempt:
    post: top_saucer_feature_started
    wait_for: top_saucer_feature_ended

queue_event_player:
  # Signal all the running saucer feature modes that they can be collected.  
  # All collectable features will be queued and collected in priority order. 
  # This allows one shot to the saucer to collect multiple features. 
  right_saucer_feature_end:
    queue_event: right_saucer_feature_ending
    events_when_finished: right_saucer_feature_ended

event_player:
  right_saucer_feature_started: 
    - start_right_saucer_score_5k
  timer_right_saucer_score_5k_tick:
    - score_100
  timer_right_saucer_score_5k_complete:
    - right_saucer_feature_end

  top_saucer_feature_started:
    - start_top_saucer_score_5k
  timer_top_saucer_score_5k_tick:
    - score_1k
  timer_top_saucer_score_5k_complete:
    - top_saucer_feature_ended
   
timers:
  right_saucer_score_5k:
    start_value: 5 
    end_value: 0
    direction: down
    tick_interval: 100ms
    control_events:
      - action: restart
        event: start_right_saucer_score_5k 
  top_saucer_score_5k:
    start_value: 5 
    end_value: 0
    direction: down
    tick_interval: 100ms
    control_events:
      - action: restart
        event: start_top_saucer_score_5k 
         
score_queue_player:
  score_10_points:
    score: 10
  score_50_points:
    score: 50
  s_right_inner_outline_active:
    score: 100 
  s_left_inner_outline_active:
    score: 100 
  s_left_center_drop_target_active:
    score: 10
  s_left_out_top_drop_target_active:
    score: 10 
  s_left_in_top_drop_target_active:
    score: 10 
  s_right_in_top_drop_target_active:
    score: 10 
  s_right_out_top_drop_target_active:
    score: 10 
  score_spinner:
    score: 100 * current_player.spinner_multiplier
  score_saucer:
    score: 5000 
  score_outlane:
    score: 5000 
  score_inlane:
    score: 5000 
  score_slingshot:
    score: 10 
  score_thumper:
    score: 100 * current_player.pops_multiplier
  score_advance_bonus:
    score: 1000
  score_10k:
    score: 10000
  score_1k:
    score: 1000
  score_100:
    score: 100
  s_spinner_active:
    score: 100 * current_player.spinner_multiplier
  
light_player:
  "{current_player.bonus%10>=1}":
    l_bonus_10000: on
  "{current_player.bonus%10>=2}":
    l_bonus_20000: on
  "{current_player.bonus%10>=3}":
    l_bonus_30000: on
  "{current_player.bonus%10>=4}":
    l_bonus_40000: on
  "{current_player.bonus%10>=5}":
    l_bonus_50000: on
  "{current_player.bonus%10>=6}":
    l_bonus_60000: on
  "{current_player.bonus%10>=7}":
    l_bonus_70000: on
  "{current_player.bonus%10>=8}":
    l_bonus_80000: on
  "{current_player.bonus%10>=9}":
    l_bonus_90000: on
  "{current_player.bonus>=10}":
    l_bonus_100000: on
