#config_version=5
##! mode: super_targets

mode:
  start_events: mode_base_started
  priority: 1020

variable_player:
  mode_super_targets_started:
    bonus_collect_count:
      int: 0
      action: set
    bonus_multiplier: 
      int: 1
      action: set
  double_bonus_enabled:
    bonus_multiplier: 
      int: 2
      action: set
  bonus_advances{current_player.bonus_collect_count>0}:
    bonus_collect_count: -1
    bonus: 1 
  drop_target_hit:
    bonus_collect_count: 1
  
event_player:
  s_adv_bonus_roll_over_active:
    - bonus_advances 
  s_left_out_outline_active:
    - bonus_advances
  s_right_out_outline_active:
    - bonus_advances
  drop_target_bank_big_reds_down:
    - score_10k
  bonus_advances{current_player.bonus_collect_count>0}:
    - score_advance_bonus

light_player:
  "{current_player.bonus_collect_count>0}":
    l_advance_bonus: on
  "{current_player.bonus_multiplier==2}":
    l_double_bonus_when_lit: on
    l_saucer_feature_lites_double_bonus: on

accruals:
  super_targets_double_bonus:
    events:
      - drop_target_left_down
      - drop_target_left_out_top_down
      - drop_target_left_in_top_down 
      - drop_target_right_out_top_down
      - drop_target_right_in_top_down
    events_when_complete: saucer_lites_double_bonus_lit
    events_when_hit: drop_target_hit
  super_targets_tripple_bonus:
    events:
      - drop_target_left_down
      - drop_target_left_out_top_down
      - drop_target_left_in_top_down 
      - drop_target_right_out_top_down
      - drop_target_right_in_top_down
    enable_events: saucer_lites_double_bonus_lit
    events_when_complete: saucer_lites_tripple_bonus_lit
    events_when_hit: drop_target_hit