#config_version=5
##! mode: saucer_50k_collect 

mode:
   start_events: saucer_50k_collect_lit
   stop_events: saucer_feature_50k_collect_ended
   priority: 540

event_player:
  timer_score_50k_tick:
    - score_10k
  timer_score_50k_complete:
    - saucer_feature_50k_collected
    - super_pops_enabled
    - saucer_feature_50k_collect_ended


queue_relay_player:
  # When the right saucer is being collected, wait until we score 
  # 50k for the caucer collect.  
  right_saucer_feature_ending.4:
    post: saucer_feature_50k_collect_started
    wait_for: saucer_feature_50k_collect_ended

show_player:
   mode_saucer_50k_collect_started:
       flashing:
           show_tokens:
               lights: l_saucer_feature_scores_50k
           key: saucer_feature_50k_collectShow
           action: play
           priority: 100
           speed: 3 
   saucer_feature_50k_collect_ended:
       saucer_feature_50k_collectShow: stop

timers:
  score_50k:
    start_value: 5 
    end_value: 0
    direction: down
    tick_interval: 200ms
    control_events:
      - action: restart
        event: saucer_feature_50k_collect_started

