#config_version=5
##! mode: saucer_50k_collect 

mode:
   start_events: saucer_50k_collect_lit
   priority: 510

event_player:
   right_saucer_feature_ended:
     - super_pops_enabled

show_player:
   mode_saucer_50k_collect_started:
       flashing:
           show_tokens:
               lights: l_saucer_feature_scores_50k
           key: saucer_feature_50k_collectShow
           action: play
           priority: 100
           speed: 5 
   super_pops_enabled:
       saucer_feature_50k_collectShow: stop
