#config_version=5
##! mode: super_feature_extra_ball 


mode:
  start_events: mode_base_started
  priority: 1030

variable_player:
  mode_super_feature_extra_ball_started:
    extra_ball_collect_count:
      int: 0
      action: set
  extra_ball_lane_enabled:
    extra_ball_collect_count: 1
  extra_ball_collected:
    extra_ball_collect_count: -1
  score_inlane{settings.extra_ball_award == 1 and current_player.extra_ball_collect_count > 0}:
    extra_ball: 1 

event_player:
  score_inlane.1{current_player.extra_ball_collect_count > 0}:
    - extra_ball_collected
  score_inlane.10{settings.extra_ball_award == 2 and current_player.extra_ball_collect_count > 0}:
    - score_extra_ball

accruals:
  super_modes_collection:
    events:
      - saucer_feature_50k_collected
      - saucer_feature_lite_double_bonus_collected
      - saucer_feature_lite_spinner_collected
    events_when_complete:
      saucer_lites_extra_ball_lane_lit

light_player:
  # mode_super_feature_extra_ball_started:
  #   l_saucer_feature_lites_extra_ball_lane: off
  extra_ball_lane_enabled:
    l_saucer_feature_lites_extra_ball_lane: on
  "{current_player.extra_ball_collect_count>0}":
    l_left_outlane_extra_ball: on
    l_right_outlane_extra_ball: on
  "{current_player.setting_extra_ball==1 and current_player.extra_ball>0}":
    l_shoot_again: on 