#config_version=5
## !mode: bonus

mode_settings:
  bonus_entries:
    - event: bonus_advances
      score: 0
      player_score_entry: bonus_count
      reset_player_score_entry: True
      skip_if_zero: True

score_queue_player:
  bonus_advances:
    score: 10000
