#config_version=5

# This mode handles flashing of the spinner feature on the saucer.  

mode:
   start_events: super_spinner_collect_lit 
   stop_events: saucer_feature_lite_spinner_collect_ended
   priority: 550

event_player:
   right_saucer_feature_ending.5:
     - super_spinner_enabled
     - saucer_feature_lite_spinner_collect_ended

show_player:
   mode_lite_spinner_started:
       flashing:
           show_tokens:
               lights: l_saucer_feature_lite_spinner
           key: saucer_feature_lite_spinnerShow
           action: play
           priority: 100
           speed: 3
   right_saucer_feature_ending.5:
       saucer_feature_lite_spinnerShow: stop
