#config_version=5

# Stern Pinball v2
# Steven Kowal - 10/31/20

hardware:
  platform: lisy
lisy:
  connection: network
  network_port: 5963
  poll_hz: 50
  network_host: "192.168.7.60"

player_vars:
  bonus:
    value_type: int
    initial_value: 0
  bonus_collect_count:
    value_type: int
    initial_value: 0
  bonus_multiplier:
    value_type: int
    initial_value: 1
  
segment_displays:
    display0:
      number: 0
    display1:
      number: 1
    display2:
      number: 2
    display3:
      number: 3
    display4:
      number: 4

segment_display_player:
  # empty all displays on game start and setup info display
  game_start:
    display0:
      text: "{current_player.ball:d}"
    display1:
      text: " "
    display2:
      text: " "
    display3:
      text: " "
    display4:
      text: " "

# show score when adding players
  player_added.1{num==1}:
    display1:
      text: "{players[0].score:d}"
  player_added.2{num==2}:
    display2:
      text: "{players[1].score:d}"
  player_added.3{num==3}:
    display3:
      text: "{players[2].score:d}"
  player_added.4{num==4}:
    display4:
      text: "{players[3].score:d}"

# clear only display0 after game
  game_ended:
    display0:
      text: ""
  game_ended{machine.player1_score > 0}:
    display1:
      text: "{machine.player1_score:d}"
  game_ended{machine.player2_score > 0}:
    display2:
      text: "{machine.player2_score:d}"
  game_ended{machine.player3_score > 0}:
    display3:
      text: "{machine.player3_score:d}"
  game_ended{machine.player4_score > 0}:
    display4:
      text: "{machine.player4_score:d}"

#flash display on player turn
  # player_turn_started.1{number==1}:
  #   display1:
  #     action: flash
  # player_score_changed.1{player_num==1}:
  #   display1:
  #     action: no_flash
  # player_turn_ended.1{number==1}:
  #   display1:
  #     action: no_flash
  # player_turn_started.2{number==2}:
  #   display2:
  #     action: flash
  # player_score_changed.2{player_num==2}:
  #   display2:
  #     action: no_flash
  # player_turn_ended.2{number==2}:
  #   display2:
  #     action: no_flash
  # player_turn_started.3{number==3}:
  #   display3:
  #     action: flash
  # player_score_changed.3{player_num==3}:
  #   display3:
  #     action: no_flash
  # player_turn_ended.3{number==3}:
  #   display3:
  #     action: no_flash
  # player_turn_started.4{number==4}:
  #   display4:
  #     action: flash
  # player_score_changed.4{player_num==4}:
  #   display4:
  #     action: no_flash
  # player_turn_ended.4{number==4}:
  #   display4:
  #     action: no_flash

digital_outputs:
    flipper_enabling_relay:
        type: driver
        number: 16
        enable_events: ball_started
        disable_events: ball_will_end

game:
    balls_per_game: 3

ball_devices:
  bd_drain:
    ball_switches: s_outhole
    eject_coil: c_outhole
    eject_targets: playfield
    tags: drain, home, trough
  bd_right_saucer:
    ball_switches: s_right_saucer
    eject_coil: c_right_saucer
    eject_timeouts: 2s
  bd_top_saucer:
    ball_switches: s_top_saucer
    eject_coil: c_top_saucer
    eject_timeouts: 2s


playfields:
  playfield:
    default_source_device: bd_drain
    tags: default
    # enable_ball_search: True

lights:
  l_saucer_feature_lite_spinner:
    number: 8  
  l_saucer_feature_scores_50k:  
    number: 23 
  l_saucer_feature_lites_double_bonus:
    number: 38
  l_saucer_feature_lites_extra_ball_lane:
    number: 53
  l_saucer_feature_lites_top_center_hole:
    number: 9  
  l_lites_triple_bonus_when_list:
    number: 26 
  l_lites_special_lane:
    number: 35 
  l_bonus_10000:
    number: 0
    tags: bonus
  l_bonus_50000:
    number: 1
    tags: bonus
  l_bonus_90000:
    number: 2
    tags: bonus
  l_advance_bonus:
    number: 4
  l_spinner_1000_when_lit:
    number: 11  
  l_bb_ball_in_play:
    number: 12
  l_bb_one_player:
    number: 13
  l_bonus_20000:
    number: 15  
    tags: bonus
  l_bonus_60000:
    number: 16
    tags: bonus
  l_bonus_100000:
    number: 17
    tags: bonus
  l_left_outlane_extra_ball:  
    number: 18
  l_right_outlane_extra_ball:  
    number: 19
  l_bb_match:
    number: 25
  l_bb_game_high_to_date:
    number: 27
  l_bb_two_player:
    number: 28
  l_bb_two_up:
    number: 29
  l_bonus_30000:
    number: 30
    tags: bonus
  l_bonus_70000:
    number: 31
    tags: bonus
  l_top_pop_bumpers:
    number: 33 
  l_bottom_pop_bumper:
    number: 34 
  l_double_bonus_when_lit:
    number: 41 
  l_bb_game_over:
    number: 42 
  l_bb_three_players:
    number: 43
  l_bb_three_up:
    number: 44
  l_bonus_40000:
    number: 45 
    tags: bonus
  l_bonus_80000:
    number: 46
    tags: bonus
  l_left_outlane_special_when_list:
    number: 48 
  l_right_outlane_special_when_list:
    number: 49
  l_triple_bonus_when_list:
    number: 56
  l_tilt:
    number: 57
  l_bb_four_players:
    number: 58
  l_bb_four_up:
    number: 59


switches:
  s_Test_switch:
    number: 0
  s_credit_start:
    number: 6
    tags: start
  s_tilt:
    number: 7
  s_outhole:
    number: 8
  s_coin_switch3:
    number: 9
  s_coin_switch2:
    number: 10
  s_coin_switch1:
    number: 11
  s_right_saucer:
    number: 12
  s_top_saucer:
    number: 13
  s_adv_bonus_roll_over:
    number: 14
  s_slam:
    number: 16
  s_10_points:
    number: 21
    events_when_activated: score_10_points
  s_50_points:
    number: 22
    events_when_activated: score_50_points
  s_right_inner_outline:
    number: 23
    events_when_activated: score_inlane
  s_left_inner_outline:
    number: 24
    events_when_activated: score_inlane
  s_left_center_drop_target:
    number: 25
  s_left_out_top_drop_target:
    number: 26
  s_left_in_top_drop_target:
    number: 27
  s_right_in_top_drop_target:
    number: 28
  s_right_out_top_drop_target:
    number: 29
  s_spinner:
    number: 30 
  s_right_out_outline:
    number: 31 
    events_when_activated: score_outlane
  s_left_out_outline:
    number: 32
    events_when_activated: score_outlane
  s_slingshot_right:
    number: 36
    events_when_activated: score_slingshot
  s_slingshot_left:
    number: 37
    events_when_activated: score_slingshot
  s_thumper_center:
    number: 38
    events_when_activated: score_thumper
  s_thumper_right:
    number: 39
    events_when_activated: score_thumper
  s_thumper_left:
    number: 40
    events_when_activated: score_thumper
  
coils:
  c_chime_10:
    number: 1
  c_thumper_left:
    number: 11
    default_pulse_ms: 20
  c_chime_100:
    number: 2
  c_thumper_right:
    number: 12 
    default_pulse_ms: 20
  c_chime_1000:
    number: 3
  c_thumper_center:
    number: 13 
    default_pulse_ms: 20
  c_chime_10000:
    number: 4
    default_pulse_ms: 20
  c_outhole:
    number: 7
    default_pulse_ms: 30
  c_slingshot_right:
    number: 14 
    default_pulse_ms: 20
  c_right_saucer:
    number: 9
    default_pulse_ms: 20
  c_left_targets:
    number: 5
    default_pulse_ms: 30
  c_top_saucer:
    number: 8 
    default_pulse_ms: 20
  c_right_targets:
    number: 10 
    default_pulse_ms: 30
  c_slingshot_left:
    number: 15
    default_pulse_ms: 20
  c_knocker:
    number: 6
  c_flipper_relay:
    number: 16
  c_coin_lock_out:
    number: 17

drop_targets:
  left:
    switch: s_left_center_drop_target
  left_out_top:
    switch: s_left_out_top_drop_target
  left_in_top:
    switch: s_left_in_top_drop_target
  right_out_top:
    switch: s_right_out_top_drop_target
  right_in_top:
    switch: s_right_in_top_drop_target

drop_target_banks:
  big_reds:
    drop_targets: left, left_out_top, left_in_top, right_out_top, right_in_top
    reset_coils: c_left_targets, c_right_targets
    reset_on_complete: 1s
    reset_events:
      ball_started: 0
      machine_reset_phase_3: 0


autofire_coils:
    ac_thumper_left:
        coil: c_thumper_left
        switch: s_thumper_left
    ac_thumper_right:
        coil: c_thumper_right
        switch: s_thumper_right
    ac_thumper_center:
        coil: c_thumper_center
        switch: s_thumper_center
    ac_slingshot_right:
        coil: c_slingshot_right
        switch: s_slingshot_right
    ac_slingshot_leftscore:
        coil: c_slingshot_left
        switch: s_slingshot_left

shows:
  flashing:
    - time: 0
      lights:
          (lights): on
    - time: .5
      lights:
          (lights): off
    - time: 1
  melody_endball:
    - time: 3
      coils:
        c_chime_1000: pulse
    - time: 4
      coils:
        c_chime_100: pulse
    - time: 5
      coils:
        c_chime_10: pulse
    - time: 7
      coils:
        c_chime_10: pulse
    - time: 8
      coils:
        c_chime_100: pulse
    - time: 9
      coils:
        c_chime_1000: pulse
  melody_startball:
    - time: 0
      coils:
        c_chime_1000: pulse
    - time: 2
      coils:
        c_chime_1000: pulse
    - time: 3
      coils:
        c_chime_1000: pulse
    - time: 5
      coils:
        c_chime_1000: pulse
    - time: 6
      coils:
        c_chime_100: pulse
    - time: 7
      coils:
        c_chime_1000: pulse
    - time: 8
      coils:
        c_chime_100: pulse
    - time: 10
      coils:
        c_chime_100: pulse
    - time: 11
      coils:
        c_chime_100: pulse
    - time: 12
      coils:
        c_chime_10: pulse
    - time: 13
      coils:
        c_chime_100: pulse
    - time: 14
      coils:
        c_chime_100: pulse


score_queues:
  score:
    chimes: c_chime_10000, c_chime_1000, c_chime_100, c_chime_10,  None
    delay: 100ms

modes:
  - base
  - bonus_countdown
  - lite_spinner
  - super_spinner
  - saucer_50k_collect
  - super_pops
  - saucer_lites_double_bonus
  - super_targets