#config_version=5
## !mode: bonus_countdown

mode:
  start_events: ball_will_end
  priority: 5000

queue_relay_player:
  ball_ending:
    post: bonus_countdown_started
    wait_for: mode_bonus_countdown_ended

variable_player:
  timer_player_bonus_tick:
    bonus:
      int: -1 

event_player:
  bonus_countdown_started{current_player.bonus>0}:
    - trigger_countdown
  bonus_countdown_started{current_player.bonus==0}:
    - mode_bonus_countdown_ended
  timer_player_bonus_tick:
    - bonus_advance_score
  timer_player_bonus_complete:
    - mode_bonus_countdown_ended

timers:
  player_bonus:
    start_value: 1 * current_player.bonus
    end_value: 0
    direction: down
    tick_interval: 450ms
    control_events:
      - action: start
        event: trigger_countdown 

score_queue_player:
  bonus_advance_score:
    score: 10000 * current_player.bonus_multiplier